services:
  mysql:
    image: 'mysql:8.0'
    container_name: journalgrid_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'journalgrid'
      MYSQL_USER: 'journalgrid'
      MYSQL_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    volumes:
      - journalgrid_db_data:/var/lib/mysql

volumes:
  journalgrid_db_data:
    driver: local
